{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "owasp-dependency-track.serviceAccountName" . }}
  labels:
{{ include "owasp-dependency-track.labels" . | indent 4 }}
{{- end -}}
